name: monzo_client
description: The Monzo client written in flutter

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: 0.15.5
  intl_translation: 0.16.5
  http: 0.11.3+16
  uuid: 0.5.3
  shared_preferences: 0.4.0
  meta: 1.1.2
  fluro: ^1.3.1
  cupertino_icons: ^0.1.0
  video_player: 0.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/sunlight.mp4
  fonts:
    - family: MontserratBold
      fonts:
        - asset: fonts/montserrat_bold.ttf
    - family: MonsterratLight
      fonts:
        - asset: fonts/montserrat_light.otf
    - family: OcraExtended
      fonts:
        - asset: fonts/ocraextended.ttf
  uses-material-design: true
